version: "3"

tasks:
  get:
    desc: Get flutter dependencies
    summary: |
      Get flutter dependencies
    cmds:
      - flutter pub get

  upgrade:
    desc: Upgrade flutter dependencies
    summary: |
      Run codegen
    cmds:
      - flutter pub upgrade --major-versions

  gen:
    desc: Generate dart files
    summary: |
      Run codegen
    cmds:
      - dart run build_runner build -d


  gen:clean:
    desc: Generate dart files
    summary: |
      Run codegen
    cmds:
      - flutter clean
      - flutter pub get
      - dart run build_runner build -d

  gen:watch:
    desc: Generate dart files
    summary: |
      Watch codegen
    cmds:
      - dart run build_runner watch -d
